# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea6443f2891506fac81d14daa373847a6904314029d525ef209dec32c8ecfc534734c02c96667e0ed845d2173a16e7cb12ce45ca02a6d901e99b66a61ed1f07b

test:
  secret_key_base: 623fa7c07127e56848f9f07f2dc6bbedb8b6449682cbf651b5b29fe372625944eae86ce38ff283fca7b2b72683194949173a78d0e4f2499e2815ce1ca1cac929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
